services:
  - type: web
    name: dealshop
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: VITE_API_BASE_URL
        value: https://fullstack-dealshop2.onrender.com

